/* demo 9 starting cloud wipes, generated by gen_film_state.py; replace with a studio export */
window.xxFilmState = {
 "sheetsById": {
  "Film": {
   "staticOverrides": {
    "byObject": {
     "Cloud wipe": {
      "density": 0.94,
      "softness": 10,
      "ragged": 0.7,
      "blur": 0
     }
    }
   },
   "sequence": {
    "subUnitsPerUnit": 25,
    "length": 27.04,
    "type": "PositionalSequence",
    "tracksByObject": {
     "Cloud wipe": {
      "trackData": {
       "t000": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Cloud wipe:open",
        "keyframes": [
         {
          "id": "k0000",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.1
         },
         {
          "id": "k0001",
          "position": 0.5,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0002",
          "position": 1.18,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0003",
          "position": 1.55,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.08
         },
         {
          "id": "k0004",
          "position": 2.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0005",
          "position": 7.3,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0006",
          "position": 7.67,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.08
         },
         {
          "id": "k0007",
          "position": 8.12,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0008",
          "position": 8.7,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0009",
          "position": 9.07,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.08
         },
         {
          "id": "k0010",
          "position": 9.52,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0011",
          "position": 12.1,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0012",
          "position": 12.47,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.08
         },
         {
          "id": "k0013",
          "position": 12.92,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0014",
          "position": 13.5,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0015",
          "position": 13.87,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.08
         },
         {
          "id": "k0016",
          "position": 14.32,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0017",
          "position": 16.82,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0018",
          "position": 17.19,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.08
         },
         {
          "id": "k0019",
          "position": 17.64,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0020",
          "position": 18.22,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0021",
          "position": 18.59,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.08
         },
         {
          "id": "k0022",
          "position": 19.04,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0023",
          "position": 26.59,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0024",
          "position": 27.04,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.1
         }
        ]
       },
       "t001": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Cloud wipe:originX",
        "keyframes": [
         {
          "id": "k0025",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 62
         },
         {
          "id": "k0026",
          "position": 1.15,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 72
         },
         {
          "id": "k0027",
          "position": 2.05,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 72
         },
         {
          "id": "k0028",
          "position": 7.27,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 30
         },
         {
          "id": "k0029",
          "position": 8.17,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 30
         },
         {
          "id": "k0030",
          "position": 8.67,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 72
         },
         {
          "id": "k0031",
          "position": 9.57,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 72
         },
         {
          "id": "k0032",
          "position": 12.07,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 30
         },
         {
          "id": "k0033",
          "position": 12.97,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 30
         },
         {
          "id": "k0034",
          "position": 13.47,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 72
         },
         {
          "id": "k0035",
          "position": 14.37,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 72
         },
         {
          "id": "k0036",
          "position": 16.79,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 30
         },
         {
          "id": "k0037",
          "position": 17.69,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 30
         },
         {
          "id": "k0038",
          "position": 18.19,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 72
         },
         {
          "id": "k0039",
          "position": 19.09,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 72
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"open\"]": "t000",
       "[\"originX\"]": "t001"
      }
     },
     "Flight": {
      "trackData": {
       "t002": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:speed",
        "keyframes": [
         {
          "id": "k0040",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 2.6
         },
         {
          "id": "k0041",
          "position": 0.6,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0042",
          "position": 0.9,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0043",
          "position": 1.5,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 3.0
         },
         {
          "id": "k0044",
          "position": 2.1,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0045",
          "position": 7.02,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0046",
          "position": 7.62,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 3.0
         },
         {
          "id": "k0047",
          "position": 8.22,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0048",
          "position": 8.42,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0049",
          "position": 9.02,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 3.0
         },
         {
          "id": "k0050",
          "position": 9.62,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0051",
          "position": 11.82,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0052",
          "position": 12.42,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 3.0
         },
         {
          "id": "k0053",
          "position": 13.02,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0054",
          "position": 13.22,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0055",
          "position": 13.82,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 3.0
         },
         {
          "id": "k0056",
          "position": 14.42,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0057",
          "position": 16.54,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0058",
          "position": 17.14,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 3.0
         },
         {
          "id": "k0059",
          "position": 17.74,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0060",
          "position": 17.94,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0061",
          "position": 18.54,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 3.0
         },
         {
          "id": "k0062",
          "position": 19.14,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0063",
          "position": 26.34,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1
         },
         {
          "id": "k0064",
          "position": 27.04,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 2.6
         }
        ]
       },
       "t003": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:shake",
        "keyframes": [
         {
          "id": "k0065",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         },
         {
          "id": "k0066",
          "position": 0.7,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0067",
          "position": 1.2,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0068",
          "position": 1.6,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         },
         {
          "id": "k0069",
          "position": 2.1,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0070",
          "position": 7.32,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0071",
          "position": 7.72,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         },
         {
          "id": "k0072",
          "position": 8.22,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0073",
          "position": 8.72,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0074",
          "position": 9.12,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         },
         {
          "id": "k0075",
          "position": 9.62,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0076",
          "position": 12.12,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0077",
          "position": 12.52,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         },
         {
          "id": "k0078",
          "position": 13.02,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0079",
          "position": 13.52,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0080",
          "position": 13.92,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         },
         {
          "id": "k0081",
          "position": 14.42,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0082",
          "position": 16.84,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0083",
          "position": 17.24,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         },
         {
          "id": "k0084",
          "position": 17.74,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0085",
          "position": 18.24,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0086",
          "position": 18.64,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         },
         {
          "id": "k0087",
          "position": 19.14,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0088",
          "position": 26.64,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0089",
          "position": 27.04,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.3
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"speed\"]": "t002",
       "[\"shake\"]": "t003"
      }
     },
     "Clouds over the film": {
      "trackData": {
       "t004": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Clouds over the film:amount",
        "keyframes": [
         {
          "id": "k0090",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.8
         },
         {
          "id": "k0091",
          "position": 0.7,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0092",
          "position": 0.8,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0093",
          "position": 1.5,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.85
         },
         {
          "id": "k0094",
          "position": 2.2,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0095",
          "position": 6.92,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0096",
          "position": 7.62,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.85
         },
         {
          "id": "k0097",
          "position": 8.32,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0098",
          "position": 9.02,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.85
         },
         {
          "id": "k0099",
          "position": 9.72,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0100",
          "position": 11.72,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0101",
          "position": 12.42,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.85
         },
         {
          "id": "k0102",
          "position": 13.12,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0103",
          "position": 13.82,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.85
         },
         {
          "id": "k0104",
          "position": 14.52,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0105",
          "position": 16.44,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0106",
          "position": 17.14,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.85
         },
         {
          "id": "k0107",
          "position": 17.84,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0108",
          "position": 18.54,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.85
         },
         {
          "id": "k0109",
          "position": 19.24,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0110",
          "position": 26.24,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0111",
          "position": 27.04,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.8
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"amount\"]": "t004"
      }
     }
    }
   }
  }
 },
 "definitionVersion": "0.4.0",
 "revisionHistory": []
};
