"""The starting cloud wipes for demo 9 (film-clouds.html): writes film-state.js.

Cut times come from the film's own shot list (xonx-hero-video/build.py: shot lengths rounded
to whole frames at 25 fps), so a key at a cut lands on the cut. A cloud sweeps through at the
cuts into and out of the four flight shots, and across the loop seam; the other cuts stay hard
cuts, as in Legora's hero. At each wipe the flight surges, the cloud field thickens over the
footage, and the torn veil closes just before the cut and tears open on the next shot, from
alternate sides. The words never move.

    python gen_film_state.py
"""
import json, pathlib, itertools

FPS = 25
LENS = [1.6, 1.4, 1.4, 1.4, 1.9, 1.4, 1.6, 1.8, 1.4, 1.4, 1.9, 1.4, 1.4, 1.8, 1.4, 1.6, 2.2]
KINDS = ['clouds', 'live', 'live', 'live', 'structure', 'clouds', 'live', 'captable', 'clouds', 'live',
         'model', 'clouds', 'live', 'jurisdictions', 'live', 'live', 'end']
frames = list(itertools.accumulate(round(l * FPS) for l in LENS))
CUTS = [f / FPS for f in frames[:-1]]
END = frames[-1] / FPS
# a wipe wherever a flight shot begins or ends
WIPES = [c for i, c in enumerate(CUTS) if KINDS[i] == 'clouds' or KINDS[i + 1] == 'clouds']

ids = (f'k{i:04d}' for i in itertools.count())
tids = (f't{i:03d}' for i in itertools.count())
EASE = [0.5, 1, 0.5, 0]
tracks = {}


def track(obj, prop, keys, handles=EASE):
    o = tracks.setdefault(obj, {'trackData': {}, 'trackIdByPropPath': {}})
    tid = next(tids)
    o['trackIdByPropPath'][json.dumps([prop])] = tid
    keys = sorted({round(p, 3): v for p, v in keys}.items())
    o['trackData'][tid] = {'type': 'BasicKeyframedTrack', '__debugName': f'{obj}:{prop}',
                           'keyframes': [{'id': next(ids), 'position': p, 'connectedRight': True, 'handles': handles,
                                          'type': 'bezier', 'value': v} for p, v in keys]}


open_, speed, amount, ox, shake = [(0, 0.1), (0.5, 1)], [(0, 2.6), (0.6, 1)], [(0, 0.8), (0.7, 0)], [(0, 62)], [(0, 0.3), (0.7, 0)]
for k, c in enumerate(WIPES):
    side = 72 if k % 2 == 0 else 30
    open_ += [(c - 0.42, 1), (c - 0.05, 0.08), (c + 0.4, 1)]
    speed += [(c - 0.7, 1), (c - 0.1, 3.0), (c + 0.5, 1)]
    amount += [(c - 0.8, 0), (c - 0.1, 0.85), (c + 0.6, 0)]   # none over live footage: faint cloud there reads as smoke
    ox += [(c - 0.45, side), (c + 0.45, side)]
    shake += [(c - 0.4, 0), (c, 0.3), (c + 0.5, 0)]
# the loop seam: the film ends into a cloud, and the next pass opens out of it
open_ += [(END - 0.45, 1), (END, 0.1)]
speed += [(END - 0.7, 1), (END, 2.6)]
amount += [(END - 0.8, 0), (END, 0.8)]
shake += [(END - 0.4, 0), (END, 0.3)]
track('Cloud wipe', 'open', open_)
track('Cloud wipe', 'originX', ox)
track('Flight', 'speed', speed)
track('Flight', 'shake', shake)
track('Clouds over the film', 'amount', amount)

state = {'sheetsById': {'Film': {'staticOverrides': {'byObject': {
            'Cloud wipe': {'density': 0.94, 'softness': 10, 'ragged': 0.7, 'blur': 0}}},
         'sequence': {'subUnitsPerUnit': 25, 'length': END, 'type': 'PositionalSequence', 'tracksByObject': tracks}}},
         'definitionVersion': '0.4.0', 'revisionHistory': []}
out = pathlib.Path(__file__).parent / 'film-state.js'
out.write_text('/* demo 9 starting cloud wipes, generated by gen_film_state.py; replace with a studio export */\n'
               'window.xxFilmState = ' + json.dumps(state, indent=1) + ';\n')
print(out.name, 'wipes at', [round(w, 2) for w in WIPES], 'end', END)
