"""The starting choreography for demo 8 (motion.html): writes motion-state.js.

A Theatre.js project state (definitionVersion 0.4.0), written by hand so the page has
something to play before Iryna keyframes her own. 0-4 s is the intro (plays once: the flight
comes in fast through the clouds and brakes, the words surface out of the blur one after the
other); 4-16 s is the loop (cruise, a slow bank and climb, the sun drifting, a surge at the
end). Values at 4 s and 16 s match, so the loop has no seam.

When she exports her own state from the studio, that file replaces motion-state.js.

    python gen_motion_state.py
"""
import json, pathlib, itertools

INTRO, END = 4.0, 16.0
ids = (f'k{i:04d}' for i in itertools.count())
tids = (f't{i:03d}' for i in itertools.count())
EASE = [0.5, 1, 0.5, 0]          # Theatre's default: ease in and out
OUT = [0.25, 1, 0.4, 0]          # decelerating into the next key

tracks = {}


def track(obj, prop, keys, handles=EASE):
    o = tracks.setdefault(obj, {'trackData': {}, 'trackIdByPropPath': {}})
    tid = next(tids)
    o['trackIdByPropPath'][json.dumps([prop])] = tid
    o['trackData'][tid] = {
        'type': 'BasicKeyframedTrack', '__debugName': f'{obj}:{prop}',
        'keyframes': [{'id': next(ids), 'position': round(p, 3), 'connectedRight': True,
                       'handles': handles, 'type': 'bezier', 'value': v} for p, v in keys]}


# the flight: rush in, brake, cruise, bank and climb, surge, back to cruise at the seam
track('Flight', 'speed', [(0, 3.2), (2.6, 1.0), (INTRO, 1.0), (11.5, 1.0), (13.4, 2.4), (15.2, 1.0), (END, 1.0)], OUT)
track('Flight', 'push', [(0, -900), (2.8, 0), (INTRO, 0), (END, 0)], OUT)
track('Flight', 'camY', [(0, 60), (3.0, 0), (INTRO, 0), (8, -45), (12, 10), (END, 0)])
track('Flight', 'camX', [(INTRO, 0), (9, 40), (14, -30), (END, 0)])
track('Flight', 'roll', [(0, -0.05), (3.2, 0), (INTRO, 0), (8, 0.035), (12.5, -0.025), (END, 0)])
track('Flight', 'fov', [(0, 70), (3.0, 58), (INTRO, 58), (13.4, 64), (15.4, 58), (END, 58)])
# the veil over the words thins as they arrive; the far haze opens up
track('Clouds', 'front', [(0, 0.75), (2.4, 0.40), (INTRO, 0.40), (END, 0.40)])
track('Clouds', 'haze', [(0, 1300), (3.2, 2600), (INTRO, 2600), (END, 2600)])
# the sun's glow drifts a little across the loop
track('Sky', 'sunX', [(INTRO, 62), (10, 66), (END, 62)])
track('Sky', 'sunY', [(INTRO, 46), (10, 43), (END, 46)])

# the page opens inside a cloud: white, out of focus, buffeting; it tears open from the sun
track('Veil', 'open', [(0, 0), (0.35, 0), (2.3, 1)], OUT)
track('Veil', 'blur', [(0, 14), (0.35, 14), (2.0, 0)], OUT)
track('Flight', 'shake', [(0, 0.55), (2.6, 0), (INTRO, 0), (13.2, 0), (13.6, 0.32), (15.2, 0), (END, 0)], OUT)

# the words surface one after the other: out of a blur, rising
LAYERS = [('Nav', 1.0, 1.8), ('Logo', 1.0, 1.9), ('Eyebrow', 1.2, 2.1),
          ('Lede', 2.3, 3.2), ('Buttons', 2.6, 3.5), ('Right column', 2.8, 3.7), ('Situations', 3.1, 3.9)]
for name, a, b in LAYERS:
    obj = 'Text / ' + name
    track(obj, 'opacity', [(0, 0), (a, 0), (b, 1)], OUT)
    track(obj, 'y', [(0, 26), (a, 26), (b, 0)], OUT)
    track(obj, 'blur', [(0, 12), (a, 12), (b, 0)], OUT)
# the headline word by word, each tipping upright as it lands; the whole line tightens after
for i, (w, rot) in enumerate([('Beyond', -4), ('Borders', 3), ('Beyond', -3), ('Advisory', 4)]):
    obj = f'Words / {i + 1} {w}'
    a = 1.35 + i * 0.2; b = a + 0.95
    track(obj, 'opacity', [(0, 0), (a, 0), (b, 1)], OUT)
    track(obj, 'y', [(0, 40), (a, 40), (b, 0)], OUT)
    track(obj, 'blur', [(0, 10), (a, 10), (b, 0)], OUT)
    track(obj, 'rotate', [(0, rot), (a, rot), (b, 0)], OUT)
track('Text / Headline', 'tracking', [(0, 0.05), (1.4, 0.05), (3.0, 0)], OUT)

state = {
    'sheetsById': {'Hero': {
        'staticOverrides': {'byObject': {}},
        'sequence': {'subUnitsPerUnit': 30, 'length': END, 'type': 'PositionalSequence', 'tracksByObject': tracks},
    }},
    'definitionVersion': '0.4.0',
    'revisionHistory': [],
}
out = pathlib.Path(__file__).parent / 'motion-state.js'
out.write_text('/* demo 8 starting choreography, generated by gen_motion_state.py; replace with a studio export */\n'
               'window.xxMotionState = ' + json.dumps(state, indent=1) + ';\n'
               'window.xxMotionIntro = ' + str(INTRO) + ';\n')
print(out.name, sum(len(o['trackData']) for o in tracks.values()), 'tracks')
