/* demo 8 starting choreography, generated by gen_motion_state.py; replace with a studio export */
window.xxMotionState = {
 "sheetsById": {
  "Hero": {
   "staticOverrides": {
    "byObject": {}
   },
   "sequence": {
    "subUnitsPerUnit": 30,
    "length": 16.0,
    "type": "PositionalSequence",
    "tracksByObject": {
     "Flight": {
      "trackData": {
       "t000": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:speed",
        "keyframes": [
         {
          "id": "k0000",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 3.2
         },
         {
          "id": "k0001",
          "position": 2.6,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         },
         {
          "id": "k0002",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         },
         {
          "id": "k0003",
          "position": 11.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         },
         {
          "id": "k0004",
          "position": 13.4,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 2.4
         },
         {
          "id": "k0005",
          "position": 15.2,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         },
         {
          "id": "k0006",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         }
        ]
       },
       "t001": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:push",
        "keyframes": [
         {
          "id": "k0007",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": -900
         },
         {
          "id": "k0008",
          "position": 2.8,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0009",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0010",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t002": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:camY",
        "keyframes": [
         {
          "id": "k0011",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 60
         },
         {
          "id": "k0012",
          "position": 3.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0013",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0014",
          "position": 8,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": -45
         },
         {
          "id": "k0015",
          "position": 12,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 10
         },
         {
          "id": "k0016",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t003": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:camX",
        "keyframes": [
         {
          "id": "k0017",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0018",
          "position": 9,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 40
         },
         {
          "id": "k0019",
          "position": 14,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": -30
         },
         {
          "id": "k0020",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t004": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:roll",
        "keyframes": [
         {
          "id": "k0021",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": -0.05
         },
         {
          "id": "k0022",
          "position": 3.2,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0023",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0024",
          "position": 8,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.035
         },
         {
          "id": "k0025",
          "position": 12.5,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": -0.025
         },
         {
          "id": "k0026",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t005": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:fov",
        "keyframes": [
         {
          "id": "k0027",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 70
         },
         {
          "id": "k0028",
          "position": 3.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 58
         },
         {
          "id": "k0029",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 58
         },
         {
          "id": "k0030",
          "position": 13.4,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 64
         },
         {
          "id": "k0031",
          "position": 15.4,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 58
         },
         {
          "id": "k0032",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 58
         }
        ]
       },
       "t012": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:shake",
        "keyframes": [
         {
          "id": "k0053",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0.55
         },
         {
          "id": "k0054",
          "position": 2.6,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0055",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0056",
          "position": 13.2,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0057",
          "position": 13.6,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0.32
         },
         {
          "id": "k0058",
          "position": 15.2,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0059",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"speed\"]": "t000",
       "[\"push\"]": "t001",
       "[\"camY\"]": "t002",
       "[\"camX\"]": "t003",
       "[\"roll\"]": "t004",
       "[\"fov\"]": "t005",
       "[\"shake\"]": "t012"
      }
     },
     "Clouds": {
      "trackData": {
       "t006": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Clouds:front",
        "keyframes": [
         {
          "id": "k0033",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.75
         },
         {
          "id": "k0034",
          "position": 2.4,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.4
         },
         {
          "id": "k0035",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.4
         },
         {
          "id": "k0036",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.4
         }
        ]
       },
       "t007": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Clouds:haze",
        "keyframes": [
         {
          "id": "k0037",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1300
         },
         {
          "id": "k0038",
          "position": 3.2,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 2600
         },
         {
          "id": "k0039",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 2600
         },
         {
          "id": "k0040",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 2600
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"front\"]": "t006",
       "[\"haze\"]": "t007"
      }
     },
     "Sky": {
      "trackData": {
       "t008": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Sky:sunX",
        "keyframes": [
         {
          "id": "k0041",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 62
         },
         {
          "id": "k0042",
          "position": 10,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 66
         },
         {
          "id": "k0043",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 62
         }
        ]
       },
       "t009": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Sky:sunY",
        "keyframes": [
         {
          "id": "k0044",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 46
         },
         {
          "id": "k0045",
          "position": 10,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 43
         },
         {
          "id": "k0046",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 46
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"sunX\"]": "t008",
       "[\"sunY\"]": "t009"
      }
     },
     "Veil": {
      "trackData": {
       "t010": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Veil:open",
        "keyframes": [
         {
          "id": "k0047",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.42,
           1,
           0.3,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0048",
          "position": 0.4,
          "connectedRight": true,
          "handles": [
           0.42,
           1,
           0.3,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0049",
          "position": 2.9,
          "connectedRight": true,
          "handles": [
           0.42,
           1,
           0.3,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t011": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Veil:blur",
        "keyframes": [
         {
          "id": "k0050",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 14
         },
         {
          "id": "k0051",
          "position": 0.4,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 14
         },
         {
          "id": "k0052",
          "position": 2.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"open\"]": "t010",
       "[\"blur\"]": "t011"
      }
     }
    }
   }
  }
 },
 "definitionVersion": "0.4.0",
 "revisionHistory": []
};
window.xxMotionIntro = 4.0;
