/* demo 8 starting choreography, generated by gen_motion_state.py; replace with a studio export */
window.xxMotionState = {
 "sheetsById": {
  "Hero": {
   "staticOverrides": {
    "byObject": {}
   },
   "sequence": {
    "subUnitsPerUnit": 30,
    "length": 16.0,
    "type": "PositionalSequence",
    "tracksByObject": {
     "Flight": {
      "trackData": {
       "t000": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:speed",
        "keyframes": [
         {
          "id": "k0000",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 3.2
         },
         {
          "id": "k0001",
          "position": 2.6,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         },
         {
          "id": "k0002",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         },
         {
          "id": "k0003",
          "position": 11.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         },
         {
          "id": "k0004",
          "position": 13.4,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 2.4
         },
         {
          "id": "k0005",
          "position": 15.2,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         },
         {
          "id": "k0006",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1.0
         }
        ]
       },
       "t001": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:push",
        "keyframes": [
         {
          "id": "k0007",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": -900
         },
         {
          "id": "k0008",
          "position": 2.8,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0009",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0010",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t002": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:camY",
        "keyframes": [
         {
          "id": "k0011",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 60
         },
         {
          "id": "k0012",
          "position": 3.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0013",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0014",
          "position": 8,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": -45
         },
         {
          "id": "k0015",
          "position": 12,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 10
         },
         {
          "id": "k0016",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t003": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:camX",
        "keyframes": [
         {
          "id": "k0017",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0018",
          "position": 9,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 40
         },
         {
          "id": "k0019",
          "position": 14,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": -30
         },
         {
          "id": "k0020",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t004": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:roll",
        "keyframes": [
         {
          "id": "k0021",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": -0.05
         },
         {
          "id": "k0022",
          "position": 3.2,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0023",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0024",
          "position": 8,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.035
         },
         {
          "id": "k0025",
          "position": 12.5,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": -0.025
         },
         {
          "id": "k0026",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t005": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Flight:fov",
        "keyframes": [
         {
          "id": "k0027",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 70
         },
         {
          "id": "k0028",
          "position": 3.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 58
         },
         {
          "id": "k0029",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 58
         },
         {
          "id": "k0030",
          "position": 13.4,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 64
         },
         {
          "id": "k0031",
          "position": 15.4,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 58
         },
         {
          "id": "k0032",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 58
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"speed\"]": "t000",
       "[\"push\"]": "t001",
       "[\"camY\"]": "t002",
       "[\"camX\"]": "t003",
       "[\"roll\"]": "t004",
       "[\"fov\"]": "t005"
      }
     },
     "Clouds": {
      "trackData": {
       "t006": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Clouds:front",
        "keyframes": [
         {
          "id": "k0033",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.75
         },
         {
          "id": "k0034",
          "position": 2.4,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.4
         },
         {
          "id": "k0035",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.4
         },
         {
          "id": "k0036",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 0.4
         }
        ]
       },
       "t007": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Clouds:haze",
        "keyframes": [
         {
          "id": "k0037",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 1300
         },
         {
          "id": "k0038",
          "position": 3.2,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 2600
         },
         {
          "id": "k0039",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 2600
         },
         {
          "id": "k0040",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 2600
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"front\"]": "t006",
       "[\"haze\"]": "t007"
      }
     },
     "Sky": {
      "trackData": {
       "t008": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Sky:sunX",
        "keyframes": [
         {
          "id": "k0041",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 62
         },
         {
          "id": "k0042",
          "position": 10,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 66
         },
         {
          "id": "k0043",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 62
         }
        ]
       },
       "t009": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Sky:sunY",
        "keyframes": [
         {
          "id": "k0044",
          "position": 4.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 46
         },
         {
          "id": "k0045",
          "position": 10,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 43
         },
         {
          "id": "k0046",
          "position": 16.0,
          "connectedRight": true,
          "handles": [
           0.5,
           1,
           0.5,
           0
          ],
          "type": "bezier",
          "value": 46
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"sunX\"]": "t008",
       "[\"sunY\"]": "t009"
      }
     },
     "Text / Nav": {
      "trackData": {
       "t010": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Nav:opacity",
        "keyframes": [
         {
          "id": "k0047",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0048",
          "position": 0.2,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0049",
          "position": 1.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t011": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Nav:y",
        "keyframes": [
         {
          "id": "k0050",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0051",
          "position": 0.2,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0052",
          "position": 1.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t012": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Nav:blur",
        "keyframes": [
         {
          "id": "k0053",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0054",
          "position": 0.2,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0055",
          "position": 1.0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"opacity\"]": "t010",
       "[\"y\"]": "t011",
       "[\"blur\"]": "t012"
      }
     },
     "Text / Logo": {
      "trackData": {
       "t013": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Logo:opacity",
        "keyframes": [
         {
          "id": "k0056",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0057",
          "position": 0.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0058",
          "position": 1.4,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t014": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Logo:y",
        "keyframes": [
         {
          "id": "k0059",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0060",
          "position": 0.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0061",
          "position": 1.4,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t015": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Logo:blur",
        "keyframes": [
         {
          "id": "k0062",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0063",
          "position": 0.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0064",
          "position": 1.4,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"opacity\"]": "t013",
       "[\"y\"]": "t014",
       "[\"blur\"]": "t015"
      }
     },
     "Text / Eyebrow": {
      "trackData": {
       "t016": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Eyebrow:opacity",
        "keyframes": [
         {
          "id": "k0065",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0066",
          "position": 0.8,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0067",
          "position": 1.7,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t017": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Eyebrow:y",
        "keyframes": [
         {
          "id": "k0068",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0069",
          "position": 0.8,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0070",
          "position": 1.7,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t018": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Eyebrow:blur",
        "keyframes": [
         {
          "id": "k0071",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0072",
          "position": 0.8,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0073",
          "position": 1.7,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"opacity\"]": "t016",
       "[\"y\"]": "t017",
       "[\"blur\"]": "t018"
      }
     },
     "Text / Headline": {
      "trackData": {
       "t019": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Headline:opacity",
        "keyframes": [
         {
          "id": "k0074",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0075",
          "position": 1.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0076",
          "position": 2.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t020": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Headline:y",
        "keyframes": [
         {
          "id": "k0077",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0078",
          "position": 1.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0079",
          "position": 2.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t021": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Headline:blur",
        "keyframes": [
         {
          "id": "k0080",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0081",
          "position": 1.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0082",
          "position": 2.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t022": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Headline:tracking",
        "keyframes": [
         {
          "id": "k0083",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0.06
         },
         {
          "id": "k0084",
          "position": 1.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0.06
         },
         {
          "id": "k0085",
          "position": 2.9,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"opacity\"]": "t019",
       "[\"y\"]": "t020",
       "[\"blur\"]": "t021",
       "[\"tracking\"]": "t022"
      }
     },
     "Text / Lede": {
      "trackData": {
       "t023": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Lede:opacity",
        "keyframes": [
         {
          "id": "k0086",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0087",
          "position": 1.7,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0088",
          "position": 2.8,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t024": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Lede:y",
        "keyframes": [
         {
          "id": "k0089",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0090",
          "position": 1.7,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0091",
          "position": 2.8,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t025": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Lede:blur",
        "keyframes": [
         {
          "id": "k0092",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0093",
          "position": 1.7,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0094",
          "position": 2.8,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"opacity\"]": "t023",
       "[\"y\"]": "t024",
       "[\"blur\"]": "t025"
      }
     },
     "Text / Buttons": {
      "trackData": {
       "t026": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Buttons:opacity",
        "keyframes": [
         {
          "id": "k0095",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0096",
          "position": 2.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0097",
          "position": 3.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t027": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Buttons:y",
        "keyframes": [
         {
          "id": "k0098",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0099",
          "position": 2.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0100",
          "position": 3.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t028": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Buttons:blur",
        "keyframes": [
         {
          "id": "k0101",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0102",
          "position": 2.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0103",
          "position": 3.1,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"opacity\"]": "t026",
       "[\"y\"]": "t027",
       "[\"blur\"]": "t028"
      }
     },
     "Text / Right column": {
      "trackData": {
       "t029": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Right column:opacity",
        "keyframes": [
         {
          "id": "k0104",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0105",
          "position": 2.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0106",
          "position": 3.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t030": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Right column:y",
        "keyframes": [
         {
          "id": "k0107",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0108",
          "position": 2.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0109",
          "position": 3.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t031": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Right column:blur",
        "keyframes": [
         {
          "id": "k0110",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0111",
          "position": 2.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0112",
          "position": 3.5,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"opacity\"]": "t029",
       "[\"y\"]": "t030",
       "[\"blur\"]": "t031"
      }
     },
     "Text / Situations": {
      "trackData": {
       "t032": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Situations:opacity",
        "keyframes": [
         {
          "id": "k0113",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0114",
          "position": 2.9,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         },
         {
          "id": "k0115",
          "position": 3.9,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 1
         }
        ]
       },
       "t033": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Situations:y",
        "keyframes": [
         {
          "id": "k0116",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0117",
          "position": 2.9,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 26
         },
         {
          "id": "k0118",
          "position": 3.9,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       },
       "t034": {
        "type": "BasicKeyframedTrack",
        "__debugName": "Text / Situations:blur",
        "keyframes": [
         {
          "id": "k0119",
          "position": 0,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0120",
          "position": 2.9,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 12
         },
         {
          "id": "k0121",
          "position": 3.9,
          "connectedRight": true,
          "handles": [
           0.25,
           1,
           0.4,
           0
          ],
          "type": "bezier",
          "value": 0
         }
        ]
       }
      },
      "trackIdByPropPath": {
       "[\"opacity\"]": "t032",
       "[\"y\"]": "t033",
       "[\"blur\"]": "t034"
      }
     }
    }
   }
  }
 },
 "definitionVersion": "0.4.0",
 "revisionHistory": []
};
window.xxMotionIntro = 4.0;
